"""Emit the model-specific DWN core Verilog from a checkpoint, then read it back and check it.

Scope note: this is NOT `rtlgen/` (Phase 1f). It is the one-shot emitter for Phase 1c -- it
produces the concrete, known-good artifact for ONE trained model, which is the thing the real
generator later has to reproduce. The brief's ordering exists for a reason: you cannot write a
generator before you know what it generates.

What is hand-written vs emitted:
  hand-written   rtl/lut_node.v, rtl/popcount.v, rtl/argmax.v  -- the structure and the
                 address/tie-break conventions, i.e. everything with a decision in it
  emitted        rtl/gen/dwn_core.v                            -- 50 tables and 300 wire
                 indices, i.e. everything that is pure transcription

Transcribing 50 64-bit constants by hand teaches nothing and risks a silent one-character
error, so it is emitted. To make sure the emission itself is trustworthy, this script parses
its own output back and asserts every table and every wire index against the checkpoint,
including concatenation order.

Usage:
    python exporter/emit_core.py training/artifacts/<run>_checkpoint.pt
"""

import argparse
import os
import re
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract import (load_checkpoint, layer_indices, extract_tables,  # noqa: E402
                     extract_wiring)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Default pipeline configuration. These are the defaults baked into the emitted module's
# parameters; a sweep point overrides them per config in Phase 2.
PIPE_LUT = 1
PIPE_POP = 1
PIPE_OUT = 1


def table_to_hex(row):
    """bool[2**n] -> integer where bit `addr` is row[addr]."""
    return int(np.packbits(row[::-1], bitorder='big').tobytes().hex(), 16)


def emit(ck, out_path):
    cfg = ck['config']
    n, num_classes = cfg['n'], cfg['num_classes']
    sd = ck['state_dict']

    layers = []
    for i in layer_indices(sd):
        layers.append((extract_tables(sd, i), *extract_wiring(sd, i, n)))

    input_bits = 16 * cfg['thermometer_bits']
    final_width = layers[-1][0].shape[0]
    group = final_width // num_classes
    score_w = int(np.ceil(np.log2(group + 1)))
    idx_w = max(1, int(np.ceil(np.log2(num_classes))))

    L = []
    L.append('// GENERATED by exporter/emit_core.py -- do not edit by hand.')
    L.append(f"// run        : {ck.get('run_name', '(unnamed)')}")
    L.append(f"// config     : n={n}, layers={cfg['layers']}, z={cfg['thermometer_bits']}, "
             f'classes={num_classes}')
    L.append(f"// accuracy   : final {ck['results']['final_acc']:.4f} "
             f"(software, {ck['results']['best_acc']:.4f} best epoch)")
    L.append('//')
    L.append('// Takes the FULL binarized vector so it can be driven straight from the Gate 1')
    L.append('// test vectors (x_binarized). Most of those bits feed nothing -- see the report')
    L.append('// from exporter/extract.py -- and synthesis is expected to drop them. The real')
    L.append('// board design wires only the selected bits, from the thermometer encoder.')
    L.append('')
    # Required: xsim rejects a design mixing modules with and without a timescale, and the
    # testbench declares one.
    L.append('`timescale 1ns / 1ps')
    L.append('`default_nettype none')
    L.append('')
    L.append('// Pipeline stages are parameters, not hand-placement: depth is a Phase 2 sweep')
    L.append('// axis (brief §10). Set any to 0 to compile that register out. LATENCY is the')
    L.append('// sum of the enabled stages and is emitted into dwn_core_params.vh for the')
    L.append('// testbench, so the two can never disagree about it.')
    L.append('//')
    L.append('// Placement follows measurement, not intuition: out-of-context synthesis put')
    L.append('// 10.194 ns in this module against 2.962 ns in the encoder, so the depth is in')
    L.append('// the popcount and argmax trees. Hence a stage after each of them.')
    L.append('module dwn_core #(')
    L.append('    parameter integer PIPE_LUT = 1,   // after each LUT layer')
    L.append('    parameter integer PIPE_POP = 1,   // after the popcounts')
    L.append('    parameter integer PIPE_OUT = 1    // after the argmax')
    L.append(')(')
    L.append('    input  wire clk,')
    L.append(f'    input  wire [{input_bits-1}:0] x,')
    L.append(f'    output wire [{idx_w-1}:0]    class_idx')
    L.append(');')
    L.append('')

    prev = 'x'
    for li, (tables, wiring, kind) in enumerate(layers):
        count = tables.shape[0]
        L.append(f'    // ---- layer {li}: {count} nodes, {kind} mapping ----')
        L.append(f'    wire [{count-1}:0] layer{li};')
        for j in range(count):
            # Concatenation is MSB-first, and slot 0 must land on addr[0], so the slots are
            # listed in REVERSE order here. This is the single most reversible-looking
            # decision in the whole design (docs/checkpoint-format.md §2).
            slots = ', '.join(f'{prev}[{b}]' for b in reversed(wiring[j].tolist()))
            L.append(f'    lut_node #(.N({n}), .TABLE(64\'h{table_to_hex(tables[j]):016X}))')
            L.append(f'        u_l{li}_n{j} (.addr({{{slots}}}), .out(layer{li}[{j}]));')
        L.append('')
        L.append(f'    wire [{count-1}:0] layer{li}_q;')
        L.append(f'    pipe_reg #(.WIDTH({count}), .ENABLE(PIPE_LUT)) u_pipe_l{li} '
                 f'(.clk(clk), .d(layer{li}), .q(layer{li}_q));')
        L.append('')
        prev = f'layer{li}_q'

    L.append('    // ---- output stage: contiguous per-class popcounts, then argmax ----')
    L.append(f'    wire [{num_classes*score_w-1}:0] scores;')
    for c in range(num_classes):
        lo, hi = c * group, (c + 1) * group - 1
        L.append(f'    popcount #(.WIDTH({group})) u_pc{c} '
                 f'(.bits({prev}[{hi}:{lo}]), .count(scores[{c*score_w+score_w-1}:{c*score_w}]));')
    L.append('')
    L.append(f'    wire [{num_classes*score_w-1}:0] scores_q;')
    L.append(f'    pipe_reg #(.WIDTH({num_classes*score_w}), .ENABLE(PIPE_POP)) u_pipe_pop '
             f'(.clk(clk), .d(scores), .q(scores_q));')
    L.append('')
    L.append(f'    wire [{idx_w-1}:0] idx;')
    L.append(f'    argmax #(.K({num_classes}), .W({score_w})) u_argmax '
             f'(.scores_flat(scores_q), .index(idx));')
    L.append('')
    L.append(f'    pipe_reg #(.WIDTH({idx_w}), .ENABLE(PIPE_OUT)) u_pipe_out '
             f'(.clk(clk), .d(idx), .q(class_idx));')
    L.append('')
    L.append('endmodule')
    L.append('')
    L.append('`default_nettype wire')

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(L) + '\n')

    # Latency emitted alongside the RTL so the testbench reads it from the same source that
    # generated the pipeline. Hardcoding it in the testbench is how a depth change silently
    # turns into an off-by-one comparison against the wrong vector.
    core_latency = PIPE_LUT * len(layers) + PIPE_POP + PIPE_OUT
    with open(os.path.join(os.path.dirname(out_path), 'dwn_core_params.vh'), 'w') as f:
        f.write('// GENERATED by exporter/emit_core.py -- do not edit.\n')
        f.write(f'`define DWN_CORE_LATENCY {core_latency}\n')

    return layers, input_bits, group, score_w, core_latency


def verify_emitted(path, layers, n):
    """Parse the emitted Verilog back and check it against the checkpoint.

    Without a simulator this is the only real check available, and it is a meaningful one:
    it catches a wrong table, a wrong wire index, and -- most importantly -- a reversed
    address concatenation, which is the failure mode that would otherwise survive all the
    way to Gate 1.
    """
    src = open(path).read()
    pat = re.compile(
        r"lut_node #\(\.N\(\d+\), \.TABLE\(64'h([0-9A-F]{16})\)\)\s*"
        r"u_l(\d+)_n(\d+) \(\.addr\(\{([^}]*)\}\)",
        re.MULTILINE)

    seen = 0
    for m in pat.finditer(src):
        tbl_hex, li, j = m.group(1), int(m.group(2)), int(m.group(3))
        tables, wiring, _ = layers[li]

        expect_hex = f'{table_to_hex(tables[j]):016X}'
        assert tbl_hex == expect_hex, (
            f'layer {li} node {j}: table {tbl_hex} != expected {expect_hex}')

        idx = [int(x) for x in re.findall(r'\[(\d+)\]', m.group(4))]
        # emitted MSB-first, so reversing recovers slot order (slot 0 first)
        assert idx[::-1] == wiring[j].tolist(), (
            f'layer {li} node {j}: wiring {idx[::-1]} != expected {wiring[j].tolist()} '
            '-- address bit order is wrong')
        seen += 1

    total = sum(t.shape[0] for t, _, _ in layers)
    assert seen == total, f'parsed {seen} nodes, expected {total}'
    return seen


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('checkpoint')
    # A DIRECTORY, matching emit_encoder.py -- both emitters write several files into the same
    # place (dwn_core.v, dwn_core_params.vh, thermometer_encoder.v, dwn_top.v) and Phase 2 hands
    # them one `Config.rtl_dir`. This was `--out <file>` in Phase 1, which made the two emitters
    # take different kinds of argument for the same idea.
    ap.add_argument('--outdir', default=os.path.join(REPO, 'rtl', 'gen'),
                    help='where to write dwn_core.v and dwn_core_params.vh '
                         '(default: the Phase 1 location)')
    args = ap.parse_args()

    out_path = os.path.join(args.outdir, 'dwn_core.v')
    ck = load_checkpoint(args.checkpoint)
    layers, input_bits, group, score_w, core_latency = emit(ck, out_path)

    rel = os.path.relpath(out_path, REPO)
    total = sum(t.shape[0] for t, _, _ in layers)
    print(f'wrote {rel}')
    print(f'  {total} lut_node instances, {input_bits}-bit input, '
          f'{len(layers)} layer(s)')
    print(f'  output stage: {ck["config"]["num_classes"]} x popcount({group}) '
          f'-> {score_w}-bit scores -> argmax')
    print(f'  pipeline: LUT={PIPE_LUT} POP={PIPE_POP} OUT={PIPE_OUT} '
          f'-> core latency {core_latency} cycles, II=1')
    print()

    seen = verify_emitted(out_path, layers, ck['config']['n'])
    print(f'read-back check: {seen}/{total} nodes match the checkpoint '
          '(tables + wire indices + address bit order)')
    print('  PASS')
    print()
    print('This check proves the file SAYS what the checkpoint says. It proves nothing about')
    print('how the Verilog BEHAVES -- only Gate 1 does that. Run: scripts/run_gate1.py')
    return 0


if __name__ == '__main__':
    sys.exit(main())
