"""Emit the thermometer encoder and the top-level wrapper from a checkpoint.

The encoder is the piece the DWN paper never counted. Its resource totals exclude the
binarization front end entirely (brief §6), and Mecik & Kumm measured that omission at up to
3.2x the reported LUTs. On an xcvu9p it did not matter. On a 20,800-LUT Artix-7 it may well
dominate: this model is 50 LUT6 nodes and 202 comparators.

So encoder and core are emitted as SEPARATE modules, wired together by a thin top. That is not
tidiness -- it is what makes it possible to synthesize each alone and report their areas
separately, which brief §6 says to do in every table we publish.

What gets built:
  rtl/gen/thermometer_encoder.v   202 comparators, Q3.12 signed, constants folded in
  rtl/gen/dwn_top.v               encoder -> core

Only the thermometer bits some node actually reads are given a comparator. The rest of the
3200-bit vector is tied low: no node reads them, so they cost nothing after synthesis, and
keeping the full width means the already-Gate-1-verified dwn_core does not have to change.

Usage:
    python exporter/emit_encoder.py training/artifacts/<run>_checkpoint.pt
"""

import argparse
import os
import re
import sys

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'exporter'))
from extract import (FRAC_BITS, WORD_BITS, load_checkpoint, layer_indices,  # noqa: E402
                     extract_tables, extract_wiring, quantize_thresholds, fits_in_word)


def emit_encoder(ck, used, out_path, frac_bits=FRAC_BITS, word=WORD_BITS):
    cfg = ck['config']
    z = cfg['thermometer_bits']
    thresholds = ck['thermometer']['thresholds'].numpy()
    n_features, total_bits = thresholds.shape[0], thresholds.size

    thr_q = quantize_thresholds(thresholds, frac_bits)
    if not fits_in_word(thr_q, word):
        raise SystemExit(
            f'thresholds do not fit in {word}-bit signed at Q{word-1-frac_bits}.{frac_bits}: '
            f'range [{thr_q.min()}, {thr_q.max()}]')

    L = []
    L.append('// GENERATED by exporter/emit_encoder.py -- do not edit by hand.')
    L.append(f"// run    : {ck.get('run_name', '(unnamed)')}")
    L.append(f'// format : Q{word-1-frac_bits}.{frac_bits} signed, {word}-bit features')
    L.append(f'// scope  : {used.size} comparators for {total_bits} thermometer bits '
             f'({100*used.size/total_bits:.1f}%)')
    L.append('//')
    L.append('// Each comparator is `feature > constant`, with the threshold folded to an')
    L.append('// integer at export time. Thresholds live in SCALED feature space, so the host')
    L.append('// must apply the StandardScaler before sending values -- the scaler mean/scale')
    L.append('// are in the checkpoint for exactly this reason.')
    L.append('//')
    L.append('// Undriven bits are tied low in the default assignment below. No node reads')
    L.append('// them, so synthesis should remove them entirely; if the LUT count says')
    L.append('// otherwise, that is a finding worth chasing.')
    L.append('')
    L.append('`timescale 1ns / 1ps')
    L.append('`default_nettype none')
    L.append('')
    L.append('module thermometer_encoder (')
    L.append(f'    input  wire [{n_features*word-1}:0] x_flat,   '
             f'// {n_features} features x {word} bits, feature f at [f*{word} +: {word}]')
    L.append(f'    output reg  [{total_bits-1}:0] bits')
    L.append(');')
    L.append('')
    L.append('    integer i;')
    L.append('')
    L.append('    always @* begin')
    L.append(f'        bits = {total_bits}\'b0;')

    for b in sorted(used.tolist()):
        f_idx, t_idx = divmod(int(b), z)
        t = int(thr_q[f_idx, t_idx])
        L.append(f'        bits[{b:4d}] = $signed(x_flat[{f_idx}*{word} +: {word}]) > '
                 f'$signed({word}\'sd{t});' if t >= 0 else
                 f'        bits[{b:4d}] = $signed(x_flat[{f_idx}*{word} +: {word}]) > '
                 f'-$signed({word}\'sd{-t});')

    L.append('    end')
    L.append('')
    L.append('endmodule')
    L.append('')
    L.append('`default_nettype wire')

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(L) + '\n')
    return thr_q


def emit_top(ck, out_path, total_bits, n_features, num_classes, word=WORD_BITS):
    idx_w = max(1, int(np.ceil(np.log2(num_classes))))
    L = []
    L.append('// GENERATED by exporter/emit_encoder.py -- do not edit by hand.')
    L.append('//')
    L.append('// Combinational end to end: quantized features in, class index out. No pipeline')
    L.append('// registers yet -- brief §9 wants a register between stages for II=1, and')
    L.append('// pipeline depth is a Phase 2 sweep axis, so stages get placed once synthesis')
    L.append('// shows where the critical path actually is (very likely the comparators).')
    L.append('')
    L.append('`timescale 1ns / 1ps')
    L.append('`default_nettype none')
    L.append('')
    L.append('module dwn_top (')
    L.append(f'    input  wire [{n_features*word-1}:0] x_flat,')
    L.append(f'    output wire [{idx_w-1}:0] class_idx')
    L.append(');')
    L.append('')
    L.append(f'    wire [{total_bits-1}:0] bits;')
    L.append('')
    L.append('    thermometer_encoder u_enc (.x_flat(x_flat), .bits(bits));')
    L.append('    dwn_core            u_core (.x(bits),       .class_idx(class_idx));')
    L.append('')
    L.append('endmodule')
    L.append('')
    L.append('`default_nettype wire')

    with open(out_path, 'w') as f:
        f.write('\n'.join(L) + '\n')


def verify_emitted(path, used, thr_q, z, word=WORD_BITS):
    """Parse the emitted comparators back and check every one against the checkpoint."""
    src = open(path).read()
    pat = re.compile(
        r'bits\[\s*(\d+)\] = \$signed\(x_flat\[(\d+)\*\d+ \+: \d+\]\) > '
        r'(-?)\$signed\(\d+\'sd(\d+)\);')
    seen = {}
    for m in pat.finditer(src):
        b, f_idx, neg, mag = int(m.group(1)), int(m.group(2)), m.group(3), int(m.group(4))
        seen[b] = (f_idx, -mag if neg else mag)

    assert set(seen) == set(used.tolist()), (
        f'emitted {len(seen)} comparators, expected {used.size}')
    for b, (f_got, t_got) in seen.items():
        f_exp, t_idx = divmod(int(b), z)
        t_exp = int(thr_q[f_exp, t_idx])
        assert f_got == f_exp, f'bit {b}: feature {f_got} != {f_exp}'
        assert t_got == t_exp, f'bit {b}: threshold {t_got} != {t_exp}'
    return len(seen)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('checkpoint')
    ap.add_argument('--outdir', default=os.path.join(REPO, 'rtl', 'gen'))
    args = ap.parse_args()

    ck = load_checkpoint(args.checkpoint)
    cfg = ck['config']
    n, num_classes, z = cfg['n'], cfg['num_classes'], cfg['thermometer_bits']
    thresholds = ck['thermometer']['thresholds'].numpy()
    n_features, total_bits = thresholds.shape[0], thresholds.size

    sd = ck['state_dict']
    first = layer_indices(sd)[0]
    extract_tables(sd, first)                     # shape assertions
    wiring, _ = extract_wiring(sd, first, n)
    used = np.unique(wiring)

    enc_path = os.path.join(args.outdir, 'thermometer_encoder.v')
    top_path = os.path.join(args.outdir, 'dwn_top.v')

    thr_q = emit_encoder(ck, used, enc_path)
    emit_top(ck, top_path, total_bits, n_features, num_classes)

    print(f'wrote {os.path.relpath(enc_path, REPO)}')
    print(f'  {used.size} comparators, Q{WORD_BITS-1-FRAC_BITS}.{FRAC_BITS} signed '
          f'({WORD_BITS}-bit), {total_bits - used.size} bits tied low')
    print(f'  quantized threshold range [{thr_q.min()}, {thr_q.max()}] '
          f'(fits {WORD_BITS}-bit signed)')
    print(f'wrote {os.path.relpath(top_path, REPO)}')
    print(f'  dwn_top: {n_features}x{WORD_BITS}-bit features -> class index')
    print()

    seen = verify_emitted(enc_path, used, thr_q, z)
    print(f'read-back check: {seen}/{used.size} comparators match the checkpoint '
          '(feature index + threshold constant)')
    print('  PASS')
    print()
    print('Behaviour is still unverified -- only Gate 1 proves that. Run: scripts/run_gate1.py')
    return 0


if __name__ == '__main__':
    sys.exit(main())
