// GENERATED by scripts/probe/gen_probe.py -- do not edit.
// Phase 1a LUT6 mapping probe. Throwaway diagnostic; not part of the real RTL.
`default_nettype none

// VARIANT D -- two layers, irregular learned-mapping-style permutation between.
// Expect exactly 60 LUT6 (37 + 23) and zero cost for the wiring.
module probe_d_twolayer (
  input  wire [63:0] din,
  output wire [22:0] dout
);

  wire [36:0] l1;

  // ---- layer 1 ----
  // node 0: reads bits [10, 16, 21, 23, 29, 35]
  wire [5:0] a_addr0 = {din[35], din[21], din[16], din[23], din[29], din[10]};
  localparam [63:0] a_T0 = 64'h00fa23ba21c190f4;
  assign l1[0] = a_T0[a_addr0];

  // node 1: reads bits [1, 13, 33, 52, 55, 62]
  wire [5:0] a_addr1 = {din[33], din[1], din[55], din[52], din[62], din[13]};
  localparam [63:0] a_T1 = 64'h5219893868768987;
  assign l1[1] = a_T1[a_addr1];

  // node 2: reads bits [1, 15, 18, 27, 49, 62]
  wire [5:0] a_addr2 = {din[49], din[27], din[1], din[18], din[62], din[15]};
  localparam [63:0] a_T2 = 64'h94bcbc009ff9c3aa;
  assign l1[2] = a_T2[a_addr2];

  // node 3: reads bits [12, 18, 23, 42, 49, 57]
  wire [5:0] a_addr3 = {din[23], din[18], din[12], din[49], din[42], din[57]};
  localparam [63:0] a_T3 = 64'h23bfa19873348dfd;
  assign l1[3] = a_T3[a_addr3];

  // node 4: reads bits [15, 16, 27, 36, 49, 53]
  wire [5:0] a_addr4 = {din[16], din[15], din[27], din[49], din[53], din[36]};
  localparam [63:0] a_T4 = 64'hb422d228553be59b;
  assign l1[4] = a_T4[a_addr4];

  // node 5: reads bits [0, 3, 6, 15, 21, 27]
  wire [5:0] a_addr5 = {din[6], din[27], din[3], din[0], din[21], din[15]};
  localparam [63:0] a_T5 = 64'h7d5728ebbfc30ca0;
  assign l1[5] = a_T5[a_addr5];

  // node 6: reads bits [1, 8, 30, 46, 47, 55]
  wire [5:0] a_addr6 = {din[46], din[47], din[30], din[1], din[55], din[8]};
  localparam [63:0] a_T6 = 64'h1e164030ba8cfd1a;
  assign l1[6] = a_T6[a_addr6];

  // node 7: reads bits [10, 16, 25, 32, 35, 40]
  wire [5:0] a_addr7 = {din[25], din[35], din[32], din[16], din[10], din[40]};
  localparam [63:0] a_T7 = 64'h6a4355cbfbcdc0ec;
  assign l1[7] = a_T7[a_addr7];

  // node 8: reads bits [0, 19, 25, 26, 38, 41]
  wire [5:0] a_addr8 = {din[0], din[41], din[38], din[19], din[25], din[26]};
  localparam [63:0] a_T8 = 64'hfee935ec1d865a95;
  assign l1[8] = a_T8[a_addr8];

  // node 9: reads bits [14, 36, 41, 45, 48, 62]
  wire [5:0] a_addr9 = {din[48], din[36], din[62], din[45], din[14], din[41]};
  localparam [63:0] a_T9 = 64'h5eba10cc76e2cab1;
  assign l1[9] = a_T9[a_addr9];

  // node 10: reads bits [4, 6, 10, 29, 31, 32]
  wire [5:0] a_addr10 = {din[29], din[4], din[31], din[6], din[32], din[10]};
  localparam [63:0] a_T10 = 64'h4b83f95277ed78b6;
  assign l1[10] = a_T10[a_addr10];

  // node 11: reads bits [5, 6, 7, 14, 32, 33]
  wire [5:0] a_addr11 = {din[32], din[5], din[14], din[6], din[7], din[33]};
  localparam [63:0] a_T11 = 64'ha9a7db9ae30de2c5;
  assign l1[11] = a_T11[a_addr11];

  // node 12: reads bits [6, 11, 20, 40, 46, 59]
  wire [5:0] a_addr12 = {din[6], din[20], din[40], din[11], din[59], din[46]};
  localparam [63:0] a_T12 = 64'hae05755f1264fddb;
  assign l1[12] = a_T12[a_addr12];

  // node 13: reads bits [5, 14, 18, 31, 34, 48]
  wire [5:0] a_addr13 = {din[31], din[14], din[5], din[34], din[18], din[48]};
  localparam [63:0] a_T13 = 64'h5cdf0678c463878d;
  assign l1[13] = a_T13[a_addr13];

  // node 14: reads bits [6, 13, 30, 43, 47, 58]
  wire [5:0] a_addr14 = {din[6], din[47], din[58], din[13], din[30], din[43]};
  localparam [63:0] a_T14 = 64'h1ea825fd89f4c737;
  assign l1[14] = a_T14[a_addr14];

  // node 15: reads bits [12, 20, 35, 53, 56, 63]
  wire [5:0] a_addr15 = {din[20], din[56], din[12], din[35], din[63], din[53]};
  localparam [63:0] a_T15 = 64'hbe13e8cd69fb0b74;
  assign l1[15] = a_T15[a_addr15];

  // node 16: reads bits [1, 3, 6, 33, 41, 57]
  wire [5:0] a_addr16 = {din[57], din[1], din[41], din[33], din[6], din[3]};
  localparam [63:0] a_T16 = 64'hb699483cd867b947;
  assign l1[16] = a_T16[a_addr16];

  // node 17: reads bits [3, 9, 49, 52, 57, 60]
  wire [5:0] a_addr17 = {din[52], din[60], din[9], din[3], din[49], din[57]};
  localparam [63:0] a_T17 = 64'h808dff4bd55f0593;
  assign l1[17] = a_T17[a_addr17];

  // node 18: reads bits [5, 21, 33, 40, 50, 52]
  wire [5:0] a_addr18 = {din[40], din[5], din[33], din[21], din[50], din[52]};
  localparam [63:0] a_T18 = 64'h936c00a6fd07d809;
  assign l1[18] = a_T18[a_addr18];

  // node 19: reads bits [1, 6, 20, 36, 47, 51]
  wire [5:0] a_addr19 = {din[47], din[6], din[20], din[36], din[1], din[51]};
  localparam [63:0] a_T19 = 64'hcbc08523709ae039;
  assign l1[19] = a_T19[a_addr19];

  // node 20: reads bits [11, 28, 41, 45, 47, 55]
  wire [5:0] a_addr20 = {din[11], din[45], din[55], din[47], din[28], din[41]};
  localparam [63:0] a_T20 = 64'hc199525ff682c9f4;
  assign l1[20] = a_T20[a_addr20];

  // node 21: reads bits [8, 13, 25, 41, 45, 55]
  wire [5:0] a_addr21 = {din[8], din[41], din[13], din[45], din[55], din[25]};
  localparam [63:0] a_T21 = 64'hcb142f2d512f2bfe;
  assign l1[21] = a_T21[a_addr21];

  // node 22: reads bits [12, 16, 20, 23, 33, 59]
  wire [5:0] a_addr22 = {din[16], din[20], din[12], din[33], din[23], din[59]};
  localparam [63:0] a_T22 = 64'haa448aa84f7e9241;
  assign l1[22] = a_T22[a_addr22];

  // node 23: reads bits [23, 27, 28, 34, 35, 48]
  wire [5:0] a_addr23 = {din[23], din[28], din[35], din[27], din[34], din[48]};
  localparam [63:0] a_T23 = 64'h6ca63f52693db25d;
  assign l1[23] = a_T23[a_addr23];

  // node 24: reads bits [5, 12, 33, 37, 56, 63]
  wire [5:0] a_addr24 = {din[63], din[37], din[12], din[56], din[33], din[5]};
  localparam [63:0] a_T24 = 64'h652e41a18461bcc0;
  assign l1[24] = a_T24[a_addr24];

  // node 25: reads bits [22, 31, 32, 44, 49, 59]
  wire [5:0] a_addr25 = {din[49], din[32], din[22], din[44], din[31], din[59]};
  localparam [63:0] a_T25 = 64'h2117475541d33ff1;
  assign l1[25] = a_T25[a_addr25];

  // node 26: reads bits [5, 27, 33, 35, 48, 54]
  wire [5:0] a_addr26 = {din[33], din[54], din[27], din[35], din[5], din[48]};
  localparam [63:0] a_T26 = 64'h6ed0e3a2e37bac6e;
  assign l1[26] = a_T26[a_addr26];

  // node 27: reads bits [0, 3, 5, 10, 39, 43]
  wire [5:0] a_addr27 = {din[0], din[3], din[43], din[5], din[39], din[10]};
  localparam [63:0] a_T27 = 64'h0c28ef2987a8ba87;
  assign l1[27] = a_T27[a_addr27];

  // node 28: reads bits [4, 38, 43, 48, 58, 60]
  wire [5:0] a_addr28 = {din[38], din[60], din[4], din[58], din[48], din[43]};
  localparam [63:0] a_T28 = 64'hbd0068c6701e7d7b;
  assign l1[28] = a_T28[a_addr28];

  // node 29: reads bits [5, 10, 33, 45, 46, 48]
  wire [5:0] a_addr29 = {din[5], din[48], din[45], din[10], din[33], din[46]};
  localparam [63:0] a_T29 = 64'h7b1b8bf41ddbb1cf;
  assign l1[29] = a_T29[a_addr29];

  // node 30: reads bits [7, 11, 22, 29, 40, 53]
  wire [5:0] a_addr30 = {din[40], din[53], din[22], din[11], din[29], din[7]};
  localparam [63:0] a_T30 = 64'hb596d9b78186d4ae;
  assign l1[30] = a_T30[a_addr30];

  // node 31: reads bits [16, 38, 45, 48, 50, 55]
  wire [5:0] a_addr31 = {din[45], din[55], din[38], din[50], din[16], din[48]};
  localparam [63:0] a_T31 = 64'h89f9eb32ad83d935;
  assign l1[31] = a_T31[a_addr31];

  // node 32: reads bits [1, 9, 17, 21, 28, 39]
  wire [5:0] a_addr32 = {din[1], din[28], din[39], din[21], din[9], din[17]};
  localparam [63:0] a_T32 = 64'h8c9982e663596513;
  assign l1[32] = a_T32[a_addr32];

  // node 33: reads bits [0, 26, 38, 55, 59, 62]
  wire [5:0] a_addr33 = {din[59], din[62], din[55], din[0], din[38], din[26]};
  localparam [63:0] a_T33 = 64'h031600b1d7ecc603;
  assign l1[33] = a_T33[a_addr33];

  // node 34: reads bits [2, 28, 34, 50, 55, 62]
  wire [5:0] a_addr34 = {din[55], din[2], din[34], din[62], din[28], din[50]};
  localparam [63:0] a_T34 = 64'hba2bc5ccc52cfad3;
  assign l1[34] = a_T34[a_addr34];

  // node 35: reads bits [21, 33, 39, 44, 60, 62]
  wire [5:0] a_addr35 = {din[39], din[21], din[60], din[44], din[62], din[33]};
  localparam [63:0] a_T35 = 64'h9e4a6bf87eaa3ce0;
  assign l1[35] = a_T35[a_addr35];

  // node 36: reads bits [2, 8, 16, 28, 41, 47]
  wire [5:0] a_addr36 = {din[41], din[28], din[2], din[8], din[47], din[16]};
  localparam [63:0] a_T36 = 64'h651aa01374dc3fd0;
  assign l1[36] = a_T36[a_addr36];
  // ---- layer 2 ----
  // node 0: reads bits [14, 18, 22, 24, 26, 34]
  wire [5:0] b_addr0 = {l1[18], l1[22], l1[26], l1[34], l1[14], l1[24]};
  localparam [63:0] b_T0 = 64'hcc9ab08fd7238ed9;
  assign dout[0] = b_T0[b_addr0];

  // node 1: reads bits [7, 11, 24, 28, 31, 33]
  wire [5:0] b_addr1 = {l1[24], l1[31], l1[7], l1[33], l1[28], l1[11]};
  localparam [63:0] b_T1 = 64'hb48efd89a31450eb;
  assign dout[1] = b_T1[b_addr1];

  // node 2: reads bits [0, 12, 19, 26, 27, 30]
  wire [5:0] b_addr2 = {l1[27], l1[26], l1[19], l1[30], l1[0], l1[12]};
  localparam [63:0] b_T2 = 64'h4a4c196238b3a264;
  assign dout[2] = b_T2[b_addr2];

  // node 3: reads bits [7, 8, 20, 23, 25, 28]
  wire [5:0] b_addr3 = {l1[23], l1[7], l1[20], l1[8], l1[28], l1[25]};
  localparam [63:0] b_T3 = 64'h94e2d4f23247670c;
  assign dout[3] = b_T3[b_addr3];

  // node 4: reads bits [2, 11, 14, 20, 24, 30]
  wire [5:0] b_addr4 = {l1[30], l1[14], l1[2], l1[20], l1[11], l1[24]};
  localparam [63:0] b_T4 = 64'hb5ec57bc3fc5426c;
  assign dout[4] = b_T4[b_addr4];

  // node 5: reads bits [8, 21, 22, 24, 25, 28]
  wire [5:0] b_addr5 = {l1[8], l1[25], l1[22], l1[21], l1[28], l1[24]};
  localparam [63:0] b_T5 = 64'hceec4ad2602b75ee;
  assign dout[5] = b_T5[b_addr5];

  // node 6: reads bits [7, 10, 22, 24, 28, 36]
  wire [5:0] b_addr6 = {l1[24], l1[36], l1[28], l1[10], l1[7], l1[22]};
  localparam [63:0] b_T6 = 64'hfa60abc53455bf6d;
  assign dout[6] = b_T6[b_addr6];

  // node 7: reads bits [0, 4, 12, 18, 27, 34]
  wire [5:0] b_addr7 = {l1[18], l1[12], l1[34], l1[0], l1[27], l1[4]};
  localparam [63:0] b_T7 = 64'h7d5e6fe58e991798;
  assign dout[7] = b_T7[b_addr7];

  // node 8: reads bits [1, 2, 5, 15, 17, 29]
  wire [5:0] b_addr8 = {l1[29], l1[5], l1[1], l1[15], l1[17], l1[2]};
  localparam [63:0] b_T8 = 64'hd70c2c6fe7c996f3;
  assign dout[8] = b_T8[b_addr8];

  // node 9: reads bits [20, 24, 25, 26, 29, 32]
  wire [5:0] b_addr9 = {l1[26], l1[29], l1[20], l1[25], l1[32], l1[24]};
  localparam [63:0] b_T9 = 64'h596501dc236f6581;
  assign dout[9] = b_T9[b_addr9];

  // node 10: reads bits [5, 13, 16, 21, 26, 27]
  wire [5:0] b_addr10 = {l1[13], l1[21], l1[27], l1[16], l1[26], l1[5]};
  localparam [63:0] b_T10 = 64'h32eaf7d36d286e72;
  assign dout[10] = b_T10[b_addr10];

  // node 11: reads bits [17, 22, 24, 26, 28, 36]
  wire [5:0] b_addr11 = {l1[24], l1[36], l1[26], l1[17], l1[28], l1[22]};
  localparam [63:0] b_T11 = 64'h0061ac926772bb6f;
  assign dout[11] = b_T11[b_addr11];

  // node 12: reads bits [16, 18, 24, 26, 31, 32]
  wire [5:0] b_addr12 = {l1[26], l1[31], l1[16], l1[32], l1[24], l1[18]};
  localparam [63:0] b_T12 = 64'h713fa447ca82a538;
  assign dout[12] = b_T12[b_addr12];

  // node 13: reads bits [2, 4, 20, 23, 24, 27]
  wire [5:0] b_addr13 = {l1[20], l1[24], l1[27], l1[2], l1[23], l1[4]};
  localparam [63:0] b_T13 = 64'hf116ad214c1e9aa7;
  assign dout[13] = b_T13[b_addr13];

  // node 14: reads bits [7, 11, 12, 20, 32, 35]
  wire [5:0] b_addr14 = {l1[7], l1[32], l1[20], l1[35], l1[12], l1[11]};
  localparam [63:0] b_T14 = 64'hc034068d0f1ea664;
  assign dout[14] = b_T14[b_addr14];

  // node 15: reads bits [13, 15, 16, 20, 24, 33]
  wire [5:0] b_addr15 = {l1[16], l1[24], l1[20], l1[13], l1[15], l1[33]};
  localparam [63:0] b_T15 = 64'h4a2fa75654999dad;
  assign dout[15] = b_T15[b_addr15];

  // node 16: reads bits [3, 10, 15, 21, 22, 30]
  wire [5:0] b_addr16 = {l1[10], l1[30], l1[3], l1[15], l1[21], l1[22]};
  localparam [63:0] b_T16 = 64'h104677e460b7ca80;
  assign dout[16] = b_T16[b_addr16];

  // node 17: reads bits [12, 19, 23, 26, 28, 34]
  wire [5:0] b_addr17 = {l1[26], l1[12], l1[19], l1[28], l1[34], l1[23]};
  localparam [63:0] b_T17 = 64'h771dbea1215e7e28;
  assign dout[17] = b_T17[b_addr17];

  // node 18: reads bits [8, 17, 18, 24, 29, 30]
  wire [5:0] b_addr18 = {l1[17], l1[30], l1[29], l1[18], l1[24], l1[8]};
  localparam [63:0] b_T18 = 64'h194e2c0de22a68ec;
  assign dout[18] = b_T18[b_addr18];

  // node 19: reads bits [3, 12, 15, 24, 25, 26]
  wire [5:0] b_addr19 = {l1[24], l1[12], l1[3], l1[15], l1[25], l1[26]};
  localparam [63:0] b_T19 = 64'h0b93f1193d639e3a;
  assign dout[19] = b_T19[b_addr19];

  // node 20: reads bits [8, 9, 12, 13, 30, 33]
  wire [5:0] b_addr20 = {l1[13], l1[9], l1[8], l1[33], l1[12], l1[30]};
  localparam [63:0] b_T20 = 64'h648cca93de997e6e;
  assign dout[20] = b_T20[b_addr20];

  // node 21: reads bits [4, 5, 6, 8, 33, 35]
  wire [5:0] b_addr21 = {l1[35], l1[33], l1[8], l1[5], l1[6], l1[4]};
  localparam [63:0] b_T21 = 64'hacaae315ed543e02;
  assign dout[21] = b_T21[b_addr21];

  // node 22: reads bits [7, 11, 12, 17, 19, 33]
  wire [5:0] b_addr22 = {l1[7], l1[19], l1[17], l1[12], l1[11], l1[33]};
  localparam [63:0] b_T22 = 64'h5d2d181ffa2a5488;
  assign dout[22] = b_T22[b_addr22];
endmodule

`default_nettype wire
