// GENERATED by scripts/probe/gen_probe.py -- do not edit.
// Phase 1a LUT6 mapping probe. Throwaway diagnostic; not part of the real RTL.
`default_nettype none

// VARIANT A -- baseline. Expect exactly 37 LUT6, 0 FF, 0 BRAM, 0 DSP.
module probe_a_baseline (
  input  wire [63:0] din,
  output wire [36:0] dout
);

  // node 0: reads bits [8, 18, 19, 21, 34, 55]
  wire [5:0] addr0 = {din[8], din[55], din[21], din[19], din[18], din[34]};
  localparam [63:0] T0 = 64'ha1bbe243a2964af0;
  assign dout[0] = T0[addr0];

  // node 1: reads bits [3, 20, 32, 40, 45, 54]
  wire [5:0] addr1 = {din[45], din[54], din[20], din[32], din[40], din[3]};
  localparam [63:0] T1 = 64'he550b917b1f74906;
  assign dout[1] = T1[addr1];

  // node 2: reads bits [4, 32, 36, 41, 55, 59]
  wire [5:0] addr2 = {din[59], din[41], din[36], din[4], din[55], din[32]};
  localparam [63:0] T2 = 64'hc7d57857dc0d24a7;
  assign dout[2] = T2[addr2];

  // node 3: reads bits [15, 35, 38, 46, 47, 55]
  wire [5:0] addr3 = {din[35], din[55], din[38], din[46], din[15], din[47]};
  localparam [63:0] T3 = 64'hea3d4750b78d8a1c;
  assign dout[3] = T3[addr3];

  // node 4: reads bits [7, 24, 26, 29, 31, 47]
  wire [5:0] addr4 = {din[24], din[31], din[7], din[47], din[29], din[26]};
  localparam [63:0] T4 = 64'h64ac11ee006786ac;
  assign dout[4] = T4[addr4];

  // node 5: reads bits [0, 1, 9, 12, 28, 54]
  wire [5:0] addr5 = {din[9], din[12], din[0], din[1], din[28], din[54]};
  localparam [63:0] T5 = 64'hba1262a730aac005;
  assign dout[5] = T5[addr5];

  // node 6: reads bits [2, 32, 35, 38, 55, 56]
  wire [5:0] addr6 = {din[55], din[2], din[38], din[56], din[35], din[32]};
  localparam [63:0] T6 = 64'he21b7223581c1fc9;
  assign dout[6] = T6[addr6];

  // node 7: reads bits [30, 31, 33, 35, 43, 57]
  wire [5:0] addr7 = {din[30], din[35], din[31], din[43], din[33], din[57]};
  localparam [63:0] T7 = 64'hac38b8be95d00d54;
  assign dout[7] = T7[addr7];

  // node 8: reads bits [9, 10, 11, 22, 28, 49]
  wire [5:0] addr8 = {din[9], din[11], din[10], din[22], din[28], din[49]};
  localparam [63:0] T8 = 64'h4c4de5254330126f;
  assign dout[8] = T8[addr8];

  // node 9: reads bits [3, 10, 48, 50, 53, 63]
  wire [5:0] addr9 = {din[53], din[3], din[50], din[48], din[10], din[63]};
  localparam [63:0] T9 = 64'hf43055de753b6baf;
  assign dout[9] = T9[addr9];

  // node 10: reads bits [5, 8, 17, 30, 47, 56]
  wire [5:0] addr10 = {din[47], din[17], din[30], din[5], din[8], din[56]};
  localparam [63:0] T10 = 64'h0d4cc6c7c350b653;
  assign dout[10] = T10[addr10];

  // node 11: reads bits [2, 3, 5, 43, 56, 61]
  wire [5:0] addr11 = {din[3], din[56], din[43], din[5], din[2], din[61]};
  localparam [63:0] T11 = 64'h3a4760e730ee2b77;
  assign dout[11] = T11[addr11];

  // node 12: reads bits [6, 7, 13, 25, 53, 58]
  wire [5:0] addr12 = {din[6], din[58], din[25], din[7], din[53], din[13]};
  localparam [63:0] T12 = 64'h715cba3b2524b608;
  assign dout[12] = T12[addr12];

  // node 13: reads bits [17, 19, 26, 33, 34, 37]
  wire [5:0] addr13 = {din[26], din[33], din[34], din[19], din[37], din[17]};
  localparam [63:0] T13 = 64'hacf7e789ad2c4054;
  assign dout[13] = T13[addr13];

  // node 14: reads bits [6, 14, 32, 33, 37, 56]
  wire [5:0] addr14 = {din[37], din[6], din[33], din[56], din[32], din[14]};
  localparam [63:0] T14 = 64'h2af361214c2586d9;
  assign dout[14] = T14[addr14];

  // node 15: reads bits [24, 25, 45, 49, 50, 58]
  wire [5:0] addr15 = {din[50], din[58], din[24], din[45], din[49], din[25]};
  localparam [63:0] T15 = 64'hee3993b9179b6a40;
  assign dout[15] = T15[addr15];

  // node 16: reads bits [6, 27, 30, 36, 39, 40]
  wire [5:0] addr16 = {din[40], din[27], din[39], din[6], din[36], din[30]};
  localparam [63:0] T16 = 64'h1ebcd5c1c9af7e27;
  assign dout[16] = T16[addr16];

  // node 17: reads bits [20, 33, 50, 51, 56, 58]
  wire [5:0] addr17 = {din[51], din[50], din[33], din[20], din[56], din[58]};
  localparam [63:0] T17 = 64'h1d4580868caf2a71;
  assign dout[17] = T17[addr17];

  // node 18: reads bits [11, 20, 34, 35, 37, 42]
  wire [5:0] addr18 = {din[11], din[35], din[20], din[34], din[37], din[42]};
  localparam [63:0] T18 = 64'hf111c2f2f878b24c;
  assign dout[18] = T18[addr18];

  // node 19: reads bits [9, 12, 40, 41, 55, 62]
  wire [5:0] addr19 = {din[41], din[62], din[40], din[9], din[55], din[12]};
  localparam [63:0] T19 = 64'h65475bfa8b3eab11;
  assign dout[19] = T19[addr19];

  // node 20: reads bits [2, 10, 27, 38, 46, 61]
  wire [5:0] addr20 = {din[38], din[46], din[2], din[61], din[27], din[10]};
  localparam [63:0] T20 = 64'h08d49a7fe65f63db;
  assign dout[20] = T20[addr20];

  // node 21: reads bits [0, 17, 27, 36, 49, 63]
  wire [5:0] addr21 = {din[36], din[63], din[0], din[17], din[49], din[27]};
  localparam [63:0] T21 = 64'hb6f3eb011b2278f3;
  assign dout[21] = T21[addr21];

  // node 22: reads bits [2, 11, 17, 26, 31, 33]
  wire [5:0] addr22 = {din[17], din[31], din[2], din[26], din[33], din[11]};
  localparam [63:0] T22 = 64'hd32c2646f140fc16;
  assign dout[22] = T22[addr22];

  // node 23: reads bits [1, 5, 26, 36, 37, 54]
  wire [5:0] addr23 = {din[1], din[36], din[5], din[54], din[26], din[37]};
  localparam [63:0] T23 = 64'h07a6928d3ec497d5;
  assign dout[23] = T23[addr23];

  // node 24: reads bits [23, 24, 27, 33, 48, 55]
  wire [5:0] addr24 = {din[23], din[33], din[24], din[48], din[27], din[55]};
  localparam [63:0] T24 = 64'h0528d8df01719bc5;
  assign dout[24] = T24[addr24];

  // node 25: reads bits [9, 14, 21, 43, 51, 56]
  wire [5:0] addr25 = {din[9], din[51], din[14], din[21], din[43], din[56]};
  localparam [63:0] T25 = 64'hcba46a1dba2809e2;
  assign dout[25] = T25[addr25];

  // node 26: reads bits [23, 32, 42, 49, 52, 59]
  wire [5:0] addr26 = {din[32], din[42], din[23], din[52], din[49], din[59]};
  localparam [63:0] T26 = 64'he00077dc44d6a3cd;
  assign dout[26] = T26[addr26];

  // node 27: reads bits [5, 14, 21, 23, 39, 42]
  wire [5:0] addr27 = {din[23], din[42], din[14], din[21], din[5], din[39]};
  localparam [63:0] T27 = 64'hd764706849a1d574;
  assign dout[27] = T27[addr27];

  // node 28: reads bits [3, 14, 27, 28, 40, 52]
  wire [5:0] addr28 = {din[14], din[52], din[3], din[27], din[28], din[40]};
  localparam [63:0] T28 = 64'hd53f0a785c5c0785;
  assign dout[28] = T28[addr28];

  // node 29: reads bits [0, 1, 6, 7, 36, 52]
  wire [5:0] addr29 = {din[7], din[1], din[6], din[52], din[0], din[36]};
  localparam [63:0] T29 = 64'h67a220f9f3ad9836;
  assign dout[29] = T29[addr29];

  // node 30: reads bits [26, 30, 36, 38, 43, 55]
  wire [5:0] addr30 = {din[55], din[38], din[26], din[30], din[36], din[43]};
  localparam [63:0] T30 = 64'h8768fac8c3e8b46c;
  assign dout[30] = T30[addr30];

  // node 31: reads bits [17, 21, 22, 23, 44, 59]
  wire [5:0] addr31 = {din[59], din[23], din[44], din[21], din[22], din[17]};
  localparam [63:0] T31 = 64'he165f6d833119bf2;
  assign dout[31] = T31[addr31];

  // node 32: reads bits [9, 13, 19, 43, 44, 53]
  wire [5:0] addr32 = {din[13], din[9], din[53], din[44], din[19], din[43]};
  localparam [63:0] T32 = 64'h44e681e08592e9ab;
  assign dout[32] = T32[addr32];

  // node 33: reads bits [3, 6, 23, 53, 59, 60]
  wire [5:0] addr33 = {din[3], din[60], din[53], din[59], din[23], din[6]};
  localparam [63:0] T33 = 64'h0777f985ea886082;
  assign dout[33] = T33[addr33];

  // node 34: reads bits [0, 6, 7, 47, 49, 52]
  wire [5:0] addr34 = {din[0], din[52], din[47], din[49], din[6], din[7]};
  localparam [63:0] T34 = 64'h7ba7685053dc8d21;
  assign dout[34] = T34[addr34];

  // node 35: reads bits [0, 10, 16, 26, 50, 57]
  wire [5:0] addr35 = {din[0], din[57], din[10], din[16], din[50], din[26]};
  localparam [63:0] T35 = 64'h180ed13284c6c76b;
  assign dout[35] = T35[addr35];

  // node 36: reads bits [28, 35, 40, 54, 57, 62]
  wire [5:0] addr36 = {din[54], din[62], din[35], din[40], din[28], din[57]};
  localparam [63:0] T36 = 64'h8fa30a5eecd6bbe1;
  assign dout[36] = T36[addr36];
endmodule

`default_nettype wire
