// GENERATED by scripts/probe/gen_probe.py -- do not edit.
// Phase 1a LUT6 mapping probe. Throwaway diagnostic; not part of the real RTL.
`default_nettype none

// VARIANT B -- table width from a parameter, `[(1<<N)-1:0]`.
// Expect exactly 37 LUT6, identical to variant A.
module lut_node_p #(
  parameter integer N = 6,
  parameter [(1<<N)-1:0] TABLE = 0
) (
  input  wire [N-1:0] addr,
  output wire         dout
);
  assign dout = TABLE[addr];
endmodule

module probe_b_param (
  input  wire [63:0] din,
  output wire [36:0] dout
);

  lut_node_p #(.N(6), .TABLE(64'ha1bbe243a2964af0)) u0 (
    .addr({din[8], din[55], din[21], din[19], din[18], din[34]}),
    .dout(dout[0])
  );

  lut_node_p #(.N(6), .TABLE(64'he550b917b1f74906)) u1 (
    .addr({din[45], din[54], din[20], din[32], din[40], din[3]}),
    .dout(dout[1])
  );

  lut_node_p #(.N(6), .TABLE(64'hc7d57857dc0d24a7)) u2 (
    .addr({din[59], din[41], din[36], din[4], din[55], din[32]}),
    .dout(dout[2])
  );

  lut_node_p #(.N(6), .TABLE(64'hea3d4750b78d8a1c)) u3 (
    .addr({din[35], din[55], din[38], din[46], din[15], din[47]}),
    .dout(dout[3])
  );

  lut_node_p #(.N(6), .TABLE(64'h64ac11ee006786ac)) u4 (
    .addr({din[24], din[31], din[7], din[47], din[29], din[26]}),
    .dout(dout[4])
  );

  lut_node_p #(.N(6), .TABLE(64'hba1262a730aac005)) u5 (
    .addr({din[9], din[12], din[0], din[1], din[28], din[54]}),
    .dout(dout[5])
  );

  lut_node_p #(.N(6), .TABLE(64'he21b7223581c1fc9)) u6 (
    .addr({din[55], din[2], din[38], din[56], din[35], din[32]}),
    .dout(dout[6])
  );

  lut_node_p #(.N(6), .TABLE(64'hac38b8be95d00d54)) u7 (
    .addr({din[30], din[35], din[31], din[43], din[33], din[57]}),
    .dout(dout[7])
  );

  lut_node_p #(.N(6), .TABLE(64'h4c4de5254330126f)) u8 (
    .addr({din[9], din[11], din[10], din[22], din[28], din[49]}),
    .dout(dout[8])
  );

  lut_node_p #(.N(6), .TABLE(64'hf43055de753b6baf)) u9 (
    .addr({din[53], din[3], din[50], din[48], din[10], din[63]}),
    .dout(dout[9])
  );

  lut_node_p #(.N(6), .TABLE(64'h0d4cc6c7c350b653)) u10 (
    .addr({din[47], din[17], din[30], din[5], din[8], din[56]}),
    .dout(dout[10])
  );

  lut_node_p #(.N(6), .TABLE(64'h3a4760e730ee2b77)) u11 (
    .addr({din[3], din[56], din[43], din[5], din[2], din[61]}),
    .dout(dout[11])
  );

  lut_node_p #(.N(6), .TABLE(64'h715cba3b2524b608)) u12 (
    .addr({din[6], din[58], din[25], din[7], din[53], din[13]}),
    .dout(dout[12])
  );

  lut_node_p #(.N(6), .TABLE(64'hacf7e789ad2c4054)) u13 (
    .addr({din[26], din[33], din[34], din[19], din[37], din[17]}),
    .dout(dout[13])
  );

  lut_node_p #(.N(6), .TABLE(64'h2af361214c2586d9)) u14 (
    .addr({din[37], din[6], din[33], din[56], din[32], din[14]}),
    .dout(dout[14])
  );

  lut_node_p #(.N(6), .TABLE(64'hee3993b9179b6a40)) u15 (
    .addr({din[50], din[58], din[24], din[45], din[49], din[25]}),
    .dout(dout[15])
  );

  lut_node_p #(.N(6), .TABLE(64'h1ebcd5c1c9af7e27)) u16 (
    .addr({din[40], din[27], din[39], din[6], din[36], din[30]}),
    .dout(dout[16])
  );

  lut_node_p #(.N(6), .TABLE(64'h1d4580868caf2a71)) u17 (
    .addr({din[51], din[50], din[33], din[20], din[56], din[58]}),
    .dout(dout[17])
  );

  lut_node_p #(.N(6), .TABLE(64'hf111c2f2f878b24c)) u18 (
    .addr({din[11], din[35], din[20], din[34], din[37], din[42]}),
    .dout(dout[18])
  );

  lut_node_p #(.N(6), .TABLE(64'h65475bfa8b3eab11)) u19 (
    .addr({din[41], din[62], din[40], din[9], din[55], din[12]}),
    .dout(dout[19])
  );

  lut_node_p #(.N(6), .TABLE(64'h08d49a7fe65f63db)) u20 (
    .addr({din[38], din[46], din[2], din[61], din[27], din[10]}),
    .dout(dout[20])
  );

  lut_node_p #(.N(6), .TABLE(64'hb6f3eb011b2278f3)) u21 (
    .addr({din[36], din[63], din[0], din[17], din[49], din[27]}),
    .dout(dout[21])
  );

  lut_node_p #(.N(6), .TABLE(64'hd32c2646f140fc16)) u22 (
    .addr({din[17], din[31], din[2], din[26], din[33], din[11]}),
    .dout(dout[22])
  );

  lut_node_p #(.N(6), .TABLE(64'h07a6928d3ec497d5)) u23 (
    .addr({din[1], din[36], din[5], din[54], din[26], din[37]}),
    .dout(dout[23])
  );

  lut_node_p #(.N(6), .TABLE(64'h0528d8df01719bc5)) u24 (
    .addr({din[23], din[33], din[24], din[48], din[27], din[55]}),
    .dout(dout[24])
  );

  lut_node_p #(.N(6), .TABLE(64'hcba46a1dba2809e2)) u25 (
    .addr({din[9], din[51], din[14], din[21], din[43], din[56]}),
    .dout(dout[25])
  );

  lut_node_p #(.N(6), .TABLE(64'he00077dc44d6a3cd)) u26 (
    .addr({din[32], din[42], din[23], din[52], din[49], din[59]}),
    .dout(dout[26])
  );

  lut_node_p #(.N(6), .TABLE(64'hd764706849a1d574)) u27 (
    .addr({din[23], din[42], din[14], din[21], din[5], din[39]}),
    .dout(dout[27])
  );

  lut_node_p #(.N(6), .TABLE(64'hd53f0a785c5c0785)) u28 (
    .addr({din[14], din[52], din[3], din[27], din[28], din[40]}),
    .dout(dout[28])
  );

  lut_node_p #(.N(6), .TABLE(64'h67a220f9f3ad9836)) u29 (
    .addr({din[7], din[1], din[6], din[52], din[0], din[36]}),
    .dout(dout[29])
  );

  lut_node_p #(.N(6), .TABLE(64'h8768fac8c3e8b46c)) u30 (
    .addr({din[55], din[38], din[26], din[30], din[36], din[43]}),
    .dout(dout[30])
  );

  lut_node_p #(.N(6), .TABLE(64'he165f6d833119bf2)) u31 (
    .addr({din[59], din[23], din[44], din[21], din[22], din[17]}),
    .dout(dout[31])
  );

  lut_node_p #(.N(6), .TABLE(64'h44e681e08592e9ab)) u32 (
    .addr({din[13], din[9], din[53], din[44], din[19], din[43]}),
    .dout(dout[32])
  );

  lut_node_p #(.N(6), .TABLE(64'h0777f985ea886082)) u33 (
    .addr({din[3], din[60], din[53], din[59], din[23], din[6]}),
    .dout(dout[33])
  );

  lut_node_p #(.N(6), .TABLE(64'h7ba7685053dc8d21)) u34 (
    .addr({din[0], din[52], din[47], din[49], din[6], din[7]}),
    .dout(dout[34])
  );

  lut_node_p #(.N(6), .TABLE(64'h180ed13284c6c76b)) u35 (
    .addr({din[0], din[57], din[10], din[16], din[50], din[26]}),
    .dout(dout[35])
  );

  lut_node_p #(.N(6), .TABLE(64'h8fa30a5eecd6bbe1)) u36 (
    .addr({din[54], din[62], din[35], din[40], din[28], din[57]}),
    .dout(dout[36])
  );

endmodule

`default_nettype wire
