"""Generate the Phase 1a LUT6 mapping probe RTL.

This is a THROWAWAY diagnostic, not a prototype of rtlgen. Its only job is to answer:
does Vivado map a DWN LUT node to exactly one LUT6 primitive?

It emits four variants, each synthesized out-of-context and counted separately:

  A  baseline      literal 64-bit localparam, `assign out = TABLE[addr]`
  B  parameterized table width from a module parameter, `[(1<<N)-1:0]`
  C  rom_style     baseline + (* rom_style = "distributed" *)
  D  two_layer     irregular inter-layer permutation, to price the "free wiring" claim

Expected result in every case: LUT6 count == node count, and zero BRAM / DSP / FF.

Tables are pseudo-random with a fixed seed so runs are reproducible. Randomness matters:
a degenerate table (all-zero, or a function of fewer than 6 inputs) would let Vivado
optimize the node away and silently corrupt the count.

Usage:  python scripts/probe/gen_probe.py
Writes: rtl/probe/*.v
"""

import random
from pathlib import Path

# Probe geometry. Node counts are deliberately non-round so a miscount is obvious
# in the utilization report rather than looking like a plausible total.
N = 6  # LUT input width -- the whole point of the probe
IN_W = 64  # input bus width (= 16 JSC features x 4 thermometer bits)
NODES = 37  # nodes in a single-layer probe
L1_NODES = 37  # two-layer probe, layer 1
L2_NODES = 23  # two-layer probe, layer 2

SEED = 20260802  # fixed for reproducibility

OUT_DIR = Path(__file__).resolve().parents[2] / "rtl" / "probe"


def make_table(rng: random.Random) -> int:
    """A non-degenerate 2**N-bit truth table.

    Rejects tables that are constant or that ignore an input, since either would let
    synthesis simplify the node and break the 1-node-1-LUT6 accounting.
    """
    size = 1 << N
    while True:
        bits = [rng.randint(0, 1) for _ in range(size)]
        if all(b == bits[0] for b in bits):
            continue  # constant function
        # reject if any input is a don't-care: flipping input i never changes output
        if any(
            all(bits[a] == bits[a ^ (1 << i)] for a in range(size)) for i in range(N)
        ):
            continue
        return int("".join(str(b) for b in reversed(bits)), 2)


def make_wiring(rng: random.Random, in_w: int) -> list[int]:
    """N distinct source-bit indices -- stands in for DWN's learned mapping."""
    return rng.sample(range(in_w), N)


def emit_nodes(rng, count, in_w, in_name, out_name, prefix, attr=""):
    """Emit `count` LUT nodes reading from `in_name`, driving `out_name`."""
    lines = []
    for i in range(count):
        table = make_table(rng)
        wiring = make_wiring(rng, in_w)
        addr = "{" + ", ".join(f"{in_name}[{b}]" for b in reversed(wiring)) + "}"
        lines.append(f"  // node {i}: reads bits {sorted(wiring)}")
        lines.append(f"  wire [{N-1}:0] {prefix}addr{i} = {addr};")
        lines.append(f"  {attr}localparam [{(1<<N)-1}:0] {prefix}T{i} = {1<<N}'h{table:016x};")
        lines.append(f"  assign {out_name}[{i}] = {prefix}T{i}[{prefix}addr{i}];")
        lines.append("")
    return lines


HEADER = """// GENERATED by scripts/probe/gen_probe.py -- do not edit.
// Phase 1a LUT6 mapping probe. Throwaway diagnostic; not part of the real RTL.
`default_nettype none

"""


def variant_a() -> str:
    rng = random.Random(SEED)
    body = emit_nodes(rng, NODES, IN_W, "din", "dout", "")
    return (
        HEADER
        + f"// VARIANT A -- baseline. Expect exactly {NODES} LUT6, 0 FF, 0 BRAM, 0 DSP.\n"
        + f"module probe_a_baseline (\n"
        f"  input  wire [{IN_W-1}:0] din,\n"
        f"  output wire [{NODES-1}:0] dout\n"
        ");\n\n" + "\n".join(body) + "endmodule\n\n`default_nettype wire\n"
    )


def variant_b() -> str:
    """Table width comes from a parameter, not a literal.

    This is the case the 'n is a Phase 2 sweep axis' decision makes mandatory: rtlgen
    must be able to emit nodes generic over N. If parameterized width infers differently
    from a literal, that is a finding we need before writing rtlgen.
    """
    rng = random.Random(SEED)
    insts = []
    for i in range(NODES):
        table = make_table(rng)
        wiring = make_wiring(rng, IN_W)
        addr = "{" + ", ".join(f"din[{b}]" for b in reversed(wiring)) + "}"
        insts.append(
            f"  lut_node_p #(.N({N}), .TABLE({1<<N}'h{table:016x})) u{i} (\n"
            f"    .addr({addr}),\n"
            f"    .dout(dout[{i}])\n"
            f"  );\n"
        )
    return (
        HEADER
        + "// VARIANT B -- table width from a parameter, `[(1<<N)-1:0]`.\n"
        + f"// Expect exactly {NODES} LUT6, identical to variant A.\n"
        + "module lut_node_p #(\n"
        "  parameter integer N = 6,\n"
        "  parameter [(1<<N)-1:0] TABLE = 0\n"
        ") (\n"
        "  input  wire [N-1:0] addr,\n"
        "  output wire         dout\n"
        ");\n"
        "  assign dout = TABLE[addr];\n"
        "endmodule\n\n"
        f"module probe_b_param (\n"
        f"  input  wire [{IN_W-1}:0] din,\n"
        f"  output wire [{NODES-1}:0] dout\n"
        ");\n\n" + "\n".join(insts) + "\nendmodule\n\n`default_nettype wire\n"
    )


def variant_c() -> str:
    rng = random.Random(SEED)
    body = emit_nodes(
        rng, NODES, IN_W, "din", "dout", "", attr='(* rom_style = "distributed" *) '
    )
    return (
        HEADER
        + "// VARIANT C -- baseline + rom_style=distributed.\n"
        + "// Only matters if A infers something other than LUT6; this is the documented fix.\n"
        + f"module probe_c_romstyle (\n"
        f"  input  wire [{IN_W-1}:0] din,\n"
        f"  output wire [{NODES-1}:0] dout\n"
        ");\n\n" + "\n".join(body) + "endmodule\n\n`default_nettype wire\n"
    )


def variant_d() -> str:
    """Two layers with irregular permutation between them.

    project-brief.md claims inter-layer wiring is 'pure wire assignment -- zero logic,
    zero cost'. If that is true, this costs exactly L1_NODES + L2_NODES LUT6 and the
    permutation is free. If routing or logic shows up here, the area model in the DSE
    plan is wrong.
    """
    rng = random.Random(SEED + 1)
    l1 = emit_nodes(rng, L1_NODES, IN_W, "din", "l1", "a_")
    l2 = emit_nodes(rng, L2_NODES, L1_NODES, "l1", "dout", "b_")
    total = L1_NODES + L2_NODES
    return (
        HEADER
        + "// VARIANT D -- two layers, irregular learned-mapping-style permutation between.\n"
        + f"// Expect exactly {total} LUT6 ({L1_NODES} + {L2_NODES}) and zero cost for the wiring.\n"
        + f"module probe_d_twolayer (\n"
        f"  input  wire [{IN_W-1}:0] din,\n"
        f"  output wire [{L2_NODES-1}:0] dout\n"
        ");\n\n"
        f"  wire [{L1_NODES-1}:0] l1;\n\n"
        "  // ---- layer 1 ----\n" + "\n".join(l1) + "  // ---- layer 2 ----\n"
        + "\n".join(l2)
        + "endmodule\n\n`default_nettype wire\n"
    )


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    variants = {
        "probe_a_baseline.v": variant_a(),
        "probe_b_param.v": variant_b(),
        "probe_c_romstyle.v": variant_c(),
        "probe_d_twolayer.v": variant_d(),
    }
    for name, text in variants.items():
        (OUT_DIR / name).write_text(text, encoding="utf-8")
        print(f"wrote {OUT_DIR / name}")

    print()
    print("expected LUT6 counts if the architectural premise holds:")
    print(f"  probe_a_baseline  {NODES}")
    print(f"  probe_b_param     {NODES}")
    print(f"  probe_c_romstyle  {NODES}")
    print(f"  probe_d_twolayer  {L1_NODES + L2_NODES}  ({L1_NODES} + {L2_NODES})")
    print("  all variants:     0 FF, 0 BRAM, 0 DSP")


if __name__ == "__main__":
    main()
