"""Generate Gate 1 test vectors for the dwn_core testbench.

Gate 1 (CLAUDE.md): the RTL is not complete until it bit-exact matches the golden software
model on EVERY test vector, INCLUDING EDGE CASES, not just the happy path. So this emits three
kinds of vector, not one:

  real     the 1000 JSC test samples from the training run, with expectations taken from
           PyTorch's own `pred` array -- the strongest reference available, since it is the
           actual model output rather than a reimplementation of it
  edge     all-zeros, all-ones, and both alternating patterns. These drive LUT addresses that
           real data may never produce. All-zeros in particular hits address 0 of every node
           simultaneously, which no natural sample is likely to do.
  random   seeded pseudorandom bit vectors, to cover address space that neither real data nor
           the patterns reach

Expectations for `edge` and `random` come from the numpy golden model in exporter/extract.py.
That model is not assumed correct -- it is re-checked against PyTorch's `pred` on the 1000 real
vectors every time this script runs, and the script refuses to emit anything if that fails.

Outputs land in build/ because they are regenerable from the committed checkpoint, and nothing
outside build/ should accumulate generated artifacts (CLAUDE.md, repo layout). They are written
next to where xsim runs so the testbench can open them by bare filename.

Usage:
    python tb/gen_vectors.py training/artifacts/<run>_checkpoint.pt
"""

import argparse
import os
import sys

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'exporter'))
from extract import (load_checkpoint, layer_indices, extract_tables,  # noqa: E402
                     extract_wiring, forward)

N_RANDOM = 500
SEED = 20260802


def bits_to_hex(row, width):
    """bool[width] -> hex string where hex bit `i` is row[i].

    Mirrors how $readmemh loads a reg vector: rightmost hex digit is bits [3:0], so the
    integer value must be sum(row[i] << i) -- the same LSB-first convention the LUT address
    uses (docs/checkpoint-format.md §2).
    """
    assert row.size == width
    return np.packbits(row[::-1].astype(np.uint8), bitorder='big').tobytes().hex()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('checkpoint')
    ap.add_argument('--vectors')
    ap.add_argument('--outdir', default=os.path.join(REPO, 'build', 'gate1'))
    args = ap.parse_args()

    ck = load_checkpoint(args.checkpoint)
    cfg = ck['config']
    n, num_classes = cfg['n'], cfg['num_classes']
    width = 16 * cfg['thermometer_bits']

    layers = []
    for i in layer_indices(ck['state_dict']):
        layers.append((extract_tables(ck['state_dict'], i),
                       *extract_wiring(ck['state_dict'], i, n)))

    vec_path = args.vectors or args.checkpoint.replace('_checkpoint.pt', '_testvectors.npz')
    v = np.load(vec_path)
    real = v['x_binarized'].astype(bool)
    real_expected = v['pred'].astype(np.int64)
    assert real.shape[1] == width, f'vector width {real.shape[1]} != expected {width}'

    # Guard: the golden model must reproduce PyTorch before it is trusted to label anything.
    golden_on_real, _ = forward(real, layers, num_classes)
    if not np.array_equal(golden_on_real, real_expected):
        bad = int((golden_on_real != real_expected).sum())
        print(f'ABORT: numpy golden model disagrees with PyTorch on {bad}/{real.shape[0]} '
              'real vectors. Not emitting test vectors -- fix the extractor first.')
        return 1

    rng = np.random.default_rng(SEED)
    edge = np.stack([
        np.zeros(width, dtype=bool),
        np.ones(width, dtype=bool),
        np.arange(width) % 2 == 0,
        np.arange(width) % 2 == 1,
    ])
    edge_names = ['all-zeros', 'all-ones', 'alternating-0101', 'alternating-1010']
    rand = rng.integers(0, 2, size=(N_RANDOM, width), dtype=np.int8).astype(bool)

    synth = np.concatenate([edge, rand])
    synth_expected, _ = forward(synth, layers, num_classes)

    x_all = np.concatenate([real, synth])
    y_all = np.concatenate([real_expected, synth_expected])
    total = x_all.shape[0]

    os.makedirs(args.outdir, exist_ok=True)
    with open(os.path.join(args.outdir, 'x_binarized.hex'), 'w') as f:
        for r in x_all:
            f.write(bits_to_hex(r, width) + '\n')
    with open(os.path.join(args.outdir, 'expected.hex'), 'w') as f:
        for y in y_all:
            f.write(f'{int(y):X}\n')
    with open(os.path.join(args.outdir, 'vec_params.vh'), 'w') as f:
        f.write('// GENERATED by tb/gen_vectors.py -- do not edit.\n')
        f.write(f'`define N_VEC {total}\n')
        f.write(f'`define VEC_W {width}\n')

    print(f'wrote {total} vectors ({width} bits each) to '
          f'{os.path.relpath(args.outdir, REPO)}')
    print(f'  {real.shape[0]:5d} real     (expected from PyTorch pred)')
    print(f'  {edge.shape[0]:5d} edge     (expected from verified golden model)')
    for name, e in zip(edge_names, synth_expected[:len(edge_names)]):
        print(f'          {name:18s} -> class {int(e)}')
    print(f'  {rand.shape[0]:5d} random   (seed {SEED})')
    print()
    print(f'golden model vs PyTorch on the real vectors: '
          f'{real.shape[0]}/{real.shape[0]} -- OK to proceed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
